/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_agency;

import Business.Customer;
import Business.MapStore;
import Business.Ticket;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author junyaoli
 */
public class MultiCityMode extends javax.swing.JPanel {

    /**
     * Creates new form MultiCityMode
     */
    private JPanel XJpanel;
    private MapStore mapstore;
    private int count=0;
    private  int key=0;
    
    public MultiCityMode(JPanel XJpanel, MapStore mapstore) {
        
        
        this.XJpanel =XJpanel;
        this.mapstore=mapstore;
        initComponents();
        seat2TextField.setVisible(false);
        flight2TextField.setVisible(false);
        seat3TextField.setVisible(false);
        flight3TextField.setVisible(false);
        jLabel5.setVisible(false);
        jLabel3.setVisible(false);
        jLabel7.setVisible(false);
        jLabel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        flight1TextField = new javax.swing.JTextField();
        reservejButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        flight2TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        flight3TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        seat1TextField = new javax.swing.JTextField();
        seat2TextField = new javax.swing.JTextField();
        seat3TextField = new javax.swing.JTextField();
        addjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 15)); // NOI18N
        jLabel1.setText("Flight Number :");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 2, 15)); // NOI18N
        jLabel2.setText("Seat Number:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 15)); // NOI18N
        jLabel4.setText("Customer  ID:");

        reservejButton.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        reservejButton.setText("Reserve");
        reservejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservejButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 15)); // NOI18N
        jLabel3.setText("Seat Number:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 15)); // NOI18N
        jLabel5.setText("Flight Number :");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 2, 15)); // NOI18N
        jLabel6.setText("Seat Number:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 2, 15)); // NOI18N
        jLabel7.setText("Flight Number :");

        addjButton.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        addjButton.setText("Add");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flight2TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seat2TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flight3TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seat3TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 171, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(flight1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seat1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(210, 210, 210))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reservejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addjButton)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flight1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(seat1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flight2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(seat2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flight3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(seat3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservejButton)
                    .addComponent(addjButton))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reservejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservejButtonActionPerformed
        
            int TID;
            int cID;
            String flightnumber; 
            String seatnumber;
            
            cID = Integer.parseInt(idTextField.getText());
            TID = key;
            flightnumber= flight1TextField.getText(); 
            seatnumber= seat1TextField.getText();    
            Ticket T1 = new Ticket(TID, cID,flightnumber, seatnumber);
            TID++;
            
            flightnumber= flight2TextField.getText(); 
            seatnumber= seat2TextField.getText();        
            Ticket T2 = new Ticket(TID, cID, flightnumber, seatnumber);
            TID++;
            
            flightnumber= flight3TextField.getText(); 
            seatnumber= seat3TextField.getText();
            Ticket T3 = new Ticket(TID, cID, flightnumber, seatnumber);
            TID++;
        
            Map<Integer, Ticket> ticketmap= MapStore.getInstance().getTicketmap();       
            Map<Integer, Customer> Customer= MapStore.getInstance().getCustomer();  
            
            if(Customer.containsKey(TID)){   
            ticketmap.put(key, T1);
            key++;
                if (count>0) {
                    ticketmap.put(key, T2);
                    ticketmap.put(key, T2);
                    key++;
                }
                if (count>1) {
                    ticketmap.put(key, T3);
                    ticketmap.put(key, T3);
                }
            System.out.println(ticketmap.get(0)+"   "+ticketmap.get(1)+"   "+ticketmap.get(2)+"  ");
            JOptionPane.showMessageDialog(null, "Reserve successfully");  
        }else{
            JOptionPane.showMessageDialog(null, "ID is not found");
        }
    }//GEN-LAST:event_reservejButtonActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
        count=count+1;
        System.out.println(count);
        if (count>0) {
            seat2TextField.setVisible(true);
            flight2TextField.setVisible(true);
            jLabel5.setVisible(true);
            jLabel3.setVisible(true);
        
        
        }if (count>1) {
            
            seat3TextField.setVisible(true);
            flight3TextField.setVisible(true);
            jLabel7.setVisible(true);
            jLabel6.setVisible(true);
        }
       XJpanel.revalidate();
    }//GEN-LAST:event_addjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JTextField flight1TextField;
    private javax.swing.JTextField flight2TextField;
    private javax.swing.JTextField flight3TextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton reservejButton;
    private javax.swing.JTextField seat1TextField;
    private javax.swing.JTextField seat2TextField;
    private javax.swing.JTextField seat3TextField;
    // End of variables declaration//GEN-END:variables
}
